# <div style="text-align:center;">Working With Tensors </div>

#### Tensors are multi-dimensional arrays that generalize the idea of scalars, vectors, and matrices. 
#### They are used to store data in various dimensions and are the building blocks for computations in machine learning and deep learning.

In [4]:
import torch
import numpy as np

### 1. Creating a Tensor

In [21]:
data = [[1, 2,],[3,4]]
data

[[1, 2], [3, 4]]

In [23]:
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [24]:
a = 5
x_a = torch.tensor(a)
x_a

tensor(5)

In [25]:
np_array = np.array(data)
np_array

array([[1, 2],
       [3, 4]])

In [27]:
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [29]:
x_ones = torch.ones_like(x_np)
x_ones

tensor([[1, 1],
        [1, 1]])

In [31]:
x_rand = torch.rand_like(x_np, dtype=torch.float)
print(f"Tensor of random numbers \n {x_rand}")

Tensor of random numbers 
 tensor([[0.2690, 0.2422],
        [0.6409, 0.7407]])


In [32]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
zeroes_tensor = torch.zeros(shape)
ones_tensor = torch.ones(shape)

In [34]:
print(f"Ones tensor: \n {ones_tensor}")

Ones tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])


### 2. Properties of a Tensor

In [37]:
# Shape, Data Type, Device
tensor = torch.rand(3,4)
print(f"Shape is {tensor.shape}")
print(f"Data type of tensor {tensor.dtype}")

Shape is torch.Size([3, 4])
Data type of tensor torch.float32


In [38]:
print(f"Device tensor is stored: {tensor.device}")

Device tensor is stored: cpu


### 3. Indexing and Slicing

In [39]:
tensor = torch.ones(4,4)

In [40]:
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [41]:
print(f"First row: {tensor[0]}")

First row: tensor([1., 1., 1., 1.])


In [42]:
print(f"First column: {tensor[:,0]}")

First column: tensor([1., 1., 1., 1.])


In [43]:
print(f"Last column: {tensor[..., -1]}")

Last column: tensor([1., 1., 1., 1.])


### 4. Combining Tensors

In [47]:
x_joined = torch.cat([tensor, tensor, tensor], dim=1)
x_joined

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### 5. Arithmetic Operations on Tensors

In [53]:
tensor_t  = tensor.T
y2 = tensor @ tensor_t
y2

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

In [52]:
y3 = tensor.matmul(tensor_t)
y3

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

In [55]:
z1 = tensor * tensor_t
z1

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [57]:
z2 = tensor.mul(tensor_t)
z2

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [60]:
agg = tensor.sum()
agg_item = agg.item()
agg_item

16.0

In [61]:
tensor.add_(5)

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])

In [62]:
tensor

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])

### 6. Tensors With Numpy

In [64]:
t = torch.ones(5)
t

tensor([1., 1., 1., 1., 1.])

In [66]:
n = t.numpy()
n

array([1., 1., 1., 1., 1.], dtype=float32)

In [67]:
t.add_(4)

tensor([5., 5., 5., 5., 5.])

In [68]:
t

tensor([5., 5., 5., 5., 5.])

In [69]:
n

array([5., 5., 5., 5., 5.], dtype=float32)

In [70]:
n = np.ones(5)

In [71]:
t = torch.from_numpy(n)

In [72]:
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)